// Emoji code to Unicode mapping for common Slack emoji
export const EMOJI_MAP = {
  // Smileys & People
  'smile': '😄', 'laughing': '😆', 'blush': '😊', 'smiley': '😃',
  'relaxed': '☺️', 'smirk': '😏', 'heart_eyes': '😍', 'kissing_heart': '😘',
  'kissing_closed_eyes': '😚', 'flushed': '😳', 'relieved': '😌',
  'satisfied': '😆', 'grin': '😁', 'wink': '😉',
  'stuck_out_tongue_winking_eye': '😜', 'stuck_out_tongue_closed_eyes': '😝',
  'grinning': '😀', 'kissing': '😗', 'kissing_smiling_eyes': '😙',
  'stuck_out_tongue': '😛', 'sleeping': '😴', 'worried': '😟',
  'frowning': '😦', 'anguished': '😧', 'open_mouth': '😮',
  'grimacing': '😬', 'confused': '😕', 'hushed': '😯',
  'expressionless': '😑', 'unamused': '😒', 'sweat_smile': '😅',
  'sweat': '😓', 'disappointed_relieved': '😥', 'weary': '😩',
  'pensive': '😔', 'disappointed': '😞', 'confounded': '😖',
  'fearful': '😨', 'cold_sweat': '😰', 'persevere': '😣',
  'cry': '😢', 'sob': '😭', 'joy': '😂', 'astonished': '😲',
  'scream': '😱', 'tired_face': '😫', 'angry': '😠', 'rage': '😡',
  'triumph': '😤', 'sleepy': '😪', 'yum': '😋', 'mask': '😷',
  'sunglasses': '😎', 'dizzy_face': '😵', 'imp': '👿',
  'smiling_imp': '😈', 'neutral_face': '😐', 'no_mouth': '😶',
  'innocent': '😇', 'alien': '👽', 'thinking_face': '🤔',
  'thinking': '🤔', 'shrug': '🤷', 'raised_eyebrow': '🤨',
  'zany_face': '🤪', 'money_mouth_face': '🤑', 'nerd_face': '🤓',
  'clown_face': '🤡', 'cowboy_hat_face': '🤠', 'partying_face': '🥳',
  'exploding_head': '🤯', 'facepalm': '🤦', 'rolling_on_the_floor_laughing': '🤣',
  'rofl': '🤣', 'slightly_smiling_face': '🙂', 'upside_down_face': '🙃',
  'hugging_face': '🤗', 'star_struck': '🤩', 'face_with_monocle': '🧐',
  'zipper_mouth_face': '🤐', 'nauseated_face': '🤢', 'sneezing_face': '🤧',
  'vomiting_face': '🤮', 'hot_face': '🥵', 'cold_face': '🥶',
  'woozy_face': '🥴', 'skull': '💀', 'ghost': '👻',
  'robot_face': '🤖', 'poop': '💩', 'hankey': '💩',

  // Hearts & Symbols
  'yellow_heart': '💛', 'blue_heart': '💙', 'purple_heart': '💜',
  'heart': '❤️', 'green_heart': '💚', 'broken_heart': '💔',
  'heartbeat': '💓', 'heartpulse': '💗', 'two_hearts': '💕',
  'revolving_hearts': '💞', 'cupid': '💘', 'sparkling_heart': '💖',
  'white_heart': '🤍', 'black_heart': '🖤', 'orange_heart': '🧡',
  'sparkles': '✨', 'star': '⭐', 'star2': '🌟', 'dizzy': '💫',
  'boom': '💥', 'collision': '💥', 'anger': '💢',
  'exclamation': '❗', 'question': '❓', 'grey_exclamation': '❕',
  'grey_question': '❔', 'zzz': '💤', 'dash': '💨',
  'sweat_drops': '💦', 'notes': '🎶', 'musical_note': '🎵',
  'fire': '🔥', '100': '💯',

  // Hands & Gestures
  '+1': '👍', 'thumbsup': '👍', '-1': '👎', 'thumbsdown': '👎',
  'ok_hand': '👌', 'punch': '👊', 'facepunch': '👊', 'fist': '✊',
  'v': '✌️', 'wave': '👋', 'hand': '✋', 'raised_hand': '✋',
  'open_hands': '👐', 'point_up': '☝️', 'point_down': '👇',
  'point_left': '👈', 'point_right': '👉', 'raised_hands': '🙌',
  'pray': '🙏', 'point_up_2': '👆', 'clap': '👏', 'muscle': '💪',
  'metal': '🤘', 'crossed_fingers': '🤞', 'love_you_gesture': '🤟',
  'call_me_hand': '🤙', 'writing_hand': '✍️', 'palms_up_together': '🤲',

  // Objects & Activities
  'rocket': '🚀', 'tada': '🎉', 'eyes': '👀', 'eye': '👁️',
  'white_check_mark': '✅', 'x': '❌', 'warning': '⚠️',
  'no_entry': '⛔', 'check': '✔️', 'heavy_check_mark': '✔️',
  'ballot_box_with_check': '☑️', 'link': '🔗', 'email': '✉️',
  'mag': '🔍', 'bulb': '💡', 'bell': '🔔', 'no_bell': '🔕',
  'mega': '📣', 'loudspeaker': '📢', 'speech_balloon': '💬',
  'thought_balloon': '💭', 'computer': '💻', 'iphone': '📱',
  'phone': '☎️', 'telephone': '☎️', 'calling': '📲',
  'memo': '📝', 'pencil': '📝', 'pencil2': '✏️',
  'book': '📖', 'books': '📚', 'notebook': '📓', 'clipboard': '📋',
  'calendar': '📆', 'date': '📅', 'card_index': '📇',
  'chart_with_upwards_trend': '📈', 'chart_with_downwards_trend': '📉',
  'bar_chart': '📊', 'file_folder': '📁', 'open_file_folder': '📂',
  'page_facing_up': '📄', 'newspaper': '📰', 'lock': '🔒',
  'unlock': '🔓', 'key': '🔑', 'package': '📦',
  'hammer': '🔨', 'wrench': '🔧', 'nut_and_bolt': '🔩', 'gear': '⚙️',
  'bomb': '💣', 'hourglass': '⌛', 'alarm_clock': '⏰', 'watch': '⌚',
  'speaker': '🔈', 'mute': '🔇', 'battery': '🔋',
  'electric_plug': '🔌', 'flashlight': '🔦', 'trophy': '🏆',
  'medal': '🏅', 'crown': '👑', 'gem': '💎', 'moneybag': '💰',
  'dollar': '💵', 'credit_card': '💳', 'gift': '🎁',
  'birthday': '🎂', 'balloon': '🎈', 'confetti_ball': '🎊',
  'party_popper': '🎉', 'ribbon': '🎀', 'soccer': '⚽',
  'basketball': '🏀', 'football': '🏈', 'baseball': '⚾',
  'tennis': '🎾', 'golf': '⛳', 'art': '🎨', 'movie_camera': '🎥',
  'camera': '📷', 'video_camera': '📹', 'microphone': '🎤',
  'headphones': '🎧', 'musical_keyboard': '🎹', 'guitar': '🎸',

  // Animals & Nature
  'dog': '🐶', 'cat': '🐱', 'mouse': '🐭', 'hamster': '🐹',
  'rabbit': '🐰', 'bear': '🐻', 'panda_face': '🐼', 'koala': '🐨',
  'tiger': '🐯', 'lion_face': '🦁', 'cow': '🐮', 'pig': '🐷',
  'frog': '🐸', 'monkey_face': '🐵', 'chicken': '🐔', 'penguin': '🐧',
  'bird': '🐦', 'eagle': '🦅', 'butterfly': '🦋', 'bug': '🐛',
  'ant': '🐜', 'bee': '🐝', 'honeybee': '🐝', 'snail': '🐌',
  'octopus': '🐙', 'turtle': '🐢', 'snake': '🐍', 'whale': '🐳',
  'dolphin': '🐬', 'fish': '🐟', 'unicorn_face': '🦄',
  'cherry_blossom': '🌸', 'tulip': '🌷', 'rose': '🌹',
  'sunflower': '🌻', 'herb': '🌿', 'four_leaf_clover': '🍀',
  'maple_leaf': '🍁', 'fallen_leaf': '🍂', 'leaves': '🍃',
  'cactus': '🌵', 'palm_tree': '🌴', 'christmas_tree': '🎄',
  'evergreen_tree': '🌲', 'deciduous_tree': '🌳',
  'rainbow': '🌈', 'sun_with_face': '🌞', 'full_moon_with_face': '🌝',
  'cloud': '☁️', 'snowflake': '❄️', 'snowman': '⛄',
  'zap': '⚡', 'cyclone': '🌀', 'ocean': '🌊',

  // Food & Drink
  'apple': '🍎', 'green_apple': '🍏', 'tangerine': '🍊',
  'lemon': '🍋', 'banana': '🍌', 'watermelon': '🍉',
  'grapes': '🍇', 'strawberry': '🍓', 'peach': '🍑',
  'cherries': '🍒', 'pineapple': '🍍', 'avocado': '🥑',
  'pizza': '🍕', 'hamburger': '🍔', 'fries': '🍟',
  'hotdog': '🌭', 'taco': '🌮', 'burrito': '🌯',
  'sushi': '🍣', 'ramen': '🍜', 'coffee': '☕',
  'tea': '🍵', 'beer': '🍺', 'beers': '🍻',
  'wine_glass': '🍷', 'cocktail': '🍸', 'tropical_drink': '🍹',
  'champagne': '🍾', 'ice_cream': '🍨', 'cake': '🍰',
  'cookie': '🍪', 'chocolate_bar': '🍫', 'candy': '🍬',
  'popcorn': '🍿', 'doughnut': '🍩',

  // Travel & Places
  'car': '🚗', 'taxi': '🚕', 'bus': '🚌', 'ambulance': '🚑',
  'fire_engine': '🚒', 'police_car': '🚓', 'truck': '🚚',
  'bike': '🚲', 'airplane': '✈️', 'helicopter': '🚁',
  'ship': '🚢', 'boat': '⛵', 'anchor': '⚓',
  'house': '🏠', 'office': '🏢', 'hospital': '🏥',
  'school': '🏫', 'church': '⛪', 'tent': '⛺',
  'earth_americas': '🌎', 'earth_africa': '🌍', 'earth_asia': '🌏',
  'globe_with_meridians': '🌐', 'world_map': '🗺️',
  'statue_of_liberty': '🗽', 'mountain': '⛰️', 'camping': '🏕️',

  // Flags & Misc
  'flag_us': '🇺🇸', 'flag_gb': '🇬🇧', 'flag_fr': '🇫🇷',
  'flag_de': '🇩🇪', 'flag_jp': '🇯🇵', 'flag_cn': '🇨🇳',
  'flag_kr': '🇰🇷', 'flag_es': '🇪🇸', 'flag_it': '🇮🇹',
  'flag_br': '🇧🇷', 'flag_ca': '🇨🇦', 'flag_au': '🇦🇺',
  'triangular_flag_on_post': '🚩', 'checkered_flag': '🏁',
  'white_flag': '🏳️', 'rainbow_flag': '🏳️‍🌈',
  'pirate_flag': '🏴‍☠️',

  // Common Slack custom-like
  'large_blue_diamond': '🔷', 'small_blue_diamond': '🔹',
  'large_orange_diamond': '🔶', 'small_orange_diamond': '🔸',
  'red_circle': '🔴', 'blue_circle': '🔵', 'white_circle': '⚪',
  'black_circle': '⚫', 'green_circle': '🟢', 'yellow_circle': '🟡',
  'orange_circle': '🟠', 'purple_circle': '🟣',
  'heavy_plus_sign': '➕', 'heavy_minus_sign': '➖',
  'heavy_division_sign': '➗', 'heavy_multiplication_x': '✖️',
  'recycle': '♻️', 'infinity': '♾️',
  'arrow_right': '➡️', 'arrow_left': '⬅️', 'arrow_up': '⬆️',
  'arrow_down': '⬇️', 'arrow_upper_right': '↗️',
  'arrow_lower_right': '↘️', 'arrow_lower_left': '↙️',
  'arrow_upper_left': '↖️', 'arrows_counterclockwise': '🔄',
  'arrow_right_hook': '↪️', 'leftwards_arrow_with_hook': '↩️',
  'pushpin': '📌', 'round_pushpin': '📍', 'scissors': '✂️',
  'paperclip': '📎', 'linked_paperclips': '🖇️',
  'wastebasket': '🗑️', 'inbox_tray': '📥', 'outbox_tray': '📤',
  'mailbox': '📫', 'mailbox_with_mail': '📬',
  'label': '🏷️', 'bookmark': '🔖', 'toolbox': '🧰',
  'shield': '🛡️', 'crossed_swords': '⚔️',
  'muscle': '💪', 'brain': '🧠', 'bone': '🦴',
  'people_holding_hands': '🧑‍🤝‍🧑', 'handshake': '🤝',
  'man_technologist': '👨‍💻', 'woman_technologist': '👩‍💻',
  'thumbs_up': '👍', 'thumbs_down': '👎'
};
